BizLand/BizLand/Areas/Admin/Controllers/TeamController.cs
using BizLand_Business.Exceptions;
using BizLand_Business.Services.Abstracts;
using BizLand_Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using FileNotFoundException = BizLand_Business.Exceptions.FileNotFoundException;

namespace BizLand.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize (Roles = "Admin")]
    public class TeamController : Controller
    {
        private readonly ITeamService _teamService;

        public TeamController(ITeamService teamService)
        {
            _teamService = teamService;
        }

        public IActionResult Index()
        {
            List<Team> teams = _teamService.GetAllTeams();
            return View(teams);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Team team)
        {
            if (!ModelState.IsValid) 
                return View();

            try
            {
                _teamService.AddTeam(team);
            }
            catch(NullReferenceException ex)
            {
                return NotFound();
            }
            catch(ImageRequireException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch(FileContentTypeException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch(FileSizeException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var existTeam = _teamService.GetTeam(x => x.Id == id);
            if (existTeam == null)
                return NotFound();

            try
            {
                _teamService.DeleteTeam(id);
            }
            catch(EntityNotFoundException ex)
            {
                return NotFound();
            }
            catch(FileNotFoundException ex)
            {
                return NotFound();
            }
            catch(Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int id)
        {
            var existTeam = _teamService.GetTeam(x => x.Id == id);
            if (existTeam == null)
                return NotFound();

            return View(existTeam);
        }

        [HttpPost]
        public IActionResult Update(int id, Team team)
        {
            if(!ModelState.IsValid)
                return View();

            try
            {
                _teamService.UpdateTeam(id, team);
            }
            catch (NullReferenceException ex)
            {
                return NotFound();
            }
            catch (ImageRequireException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (FileContentTypeException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (FileSizeException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (EntityNotFoundException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (FileNotFoundException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }



            return RedirectToAction(nameof(Index));
        }
    }
}

BizLand/BizLand/Areas/Admin/Views/Team/Create.cshtml
@using BizLand_Core.Models
@model Team

<div class="container">
	<form method="post" enctype="multipart/form-data">
		<div class="row">
            <div class="mb-3 col-md-3">
                <label asp-for="Fullname" class="form-label">FullName</label>
                <input asp-for="Fullname" class="form-control">
                <span asp-validation-for="Fullname" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-3">
                <label asp-for="Position" class="form-label">Position</label>
                <input asp-for="Position" class="form-control">
                <span asp-validation-for="Position" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-3">
                <label asp-for="ImgFile" class="form-label">ImgFile</label>
                <input asp-for="ImgFile" class="form-control">
                <span asp-validation-for="ImgFile" style="color:red"></span>
            </div>
		</div>
        <button type="submit" class="btn btn-primary" >Submit</button>
	</form>
</div>

BizLand/BizLand/Areas/Admin/Views/Team/Index.cshtml
@using BizLand_Core.Models
@model List<Team>

@{
    int count = 0;
}

<h1>
    Teams

    <a class="btn btn-primary" asp-action="Create">Create</a>
</h1>


<div class="container">
	<div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">FullName</th>
                    <th scope="col">Position</th>
                    <th scope="col">Image</th>
                </tr>
            </thead>
            <tbody>
                    @foreach(var item in Model)
                    {
                    count++;
                    <tr>
                        <td>@count</td>
                        <td>@item.Fullname</td>
                        <td>@item.Position</td>
                        <td>
                            <div style="width:100px">
                                <img width="100%" src="~/upload/team/@item.ImgUrl"/>
                            </div>
                        </td>

                        <td>
                            <a class="btn btn-warning" asp-action="Update" asp-controller="Team" asp-route-id="@item.Id">Update</a>
                            <a class="btn btn-danger" asp-action="Delete" asp-controller="Team" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>

                }             
            </tbody>
        </table>
	</div>
</div>

BizLand/BizLand/Areas/Admin/Views/Team/Update.cshtml
@using BizLand_Core.Models
@model Team

<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="mb-3 col-md-3">
                <label asp-for="Fullname" class="form-label">FullName</label>
                <input asp-for="Fullname" class="form-control">
                <span asp-validation-for="Fullname" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-3">
                <label asp-for="Position" class="form-label">Position</label>
                <input asp-for="Position" class="form-control">
                <span asp-validation-for="Position" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-3">
                <label asp-for="ImgFile" class="form-label">ImgFile</label>
                <input asp-for="ImgFile" class="form-control">
                <span asp-validation-for="ImgFile" style="color:red"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>